name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install MLX dependencies
      run : sudo apt-get update && sudo apt-get install xorg libxext-dev zlib1g-dev libbsd-dev

    - name: Mandatory compilation
      run: cd mandatory && make

    - name: Bonus compilation
      run: cd ../bonus && make
